name: Generate Pac-Man Graph

on:
  workflow_dispatch: # run manually
  schedule:
    - cron: "0 0 * * *" # run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Pac-Man Generator
        run: npm install -g github-contribution-graph

      - name: Verify Installation
        run: |
          which github-contribution-graph
          github-contribution-graph --help

      - name: Generate Pac-Man Graph
        run: github-contribution-graph pacman.svg

      - name: List Files (Debug)
        run: ls -la

      - name: Commit and Push Pac-Man graph
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pacman.svg
          git commit -m "Update Pac-Man graph" || echo "No changes to commit"
          git push
